# Generated by Django 5.2 on 2026-05-30 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produccion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('tipo_tarifa', models.CharField(choices=[('T1', 'Tarifa 1'), ('T2', 'Tarifa 2'), ('T3', 'Tarifa 3'), ('T4', 'Tarifa 4'), ('T5', 'Tarifa 5')], default='T1', max_length=2)),
                ('autoriza_datos', models.BooleanField(default=False, verbose_name='Autoriza tratamiento de datos personales (Ley 1581/2012)')),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('modalidad_pago', models.CharField(choices=[('EFE', 'Efectivo'), ('NEQ', 'Nequi'), ('CRE', 'Crédito')], max_length=3)),
                ('devolucion', models.PositiveIntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas', to='distribucion.cliente')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas', to='produccion.producto')),
            ],
            options={
                'verbose_name': 'Entrega',
                'verbose_name_plural': 'Entregas',
                'ordering': ['planilla', 'cliente'],
            },
        ),
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pagado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creditos', to='distribucion.cliente')),
                ('entrega', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='credito', to='distribucion.entrega')),
            ],
            options={
                'verbose_name': 'Crédito',
                'verbose_name_plural': 'Créditos',
                'ordering': ['pagado', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Planilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('ABR', 'Abierta'), ('PEN', 'Pendiente de validación'), ('VAL', 'Validada')], default='ABR', max_length=3)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('distribuidor', models.ForeignKey(limit_choices_to={'rol': 'DIST'}, on_delete=django.db.models.deletion.PROTECT, related_name='planillas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Planilla',
                'verbose_name_plural': 'Planillas',
                'ordering': ['-fecha'],
                'unique_together': {('fecha', 'distribuidor')},
            },
        ),
        migrations.AddField(
            model_name='entrega',
            name='planilla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='distribucion.planilla'),
        ),
        migrations.CreateModel(
            name='Averia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('descripcion', models.TextField(blank=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='averias', to='produccion.producto')),
                ('planilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='averias', to='distribucion.planilla')),
            ],
            options={
                'verbose_name': 'Avería',
                'verbose_name_plural': 'Averías',
            },
        ),
        migrations.CreateModel(
            name='PrecioCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='distribucion.cliente')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='precios_clientes', to='produccion.producto')),
            ],
            options={
                'verbose_name': 'Precio por Cliente',
                'verbose_name_plural': 'Precios por Cliente',
                'unique_together': {('cliente', 'producto')},
            },
        ),
    ]
