# Generated by Django 5.2 on 2026-06-06 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribucion', '0001_initial'),
        ('produccion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='tipo_tarifa',
        ),
        migrations.AddField(
            model_name='cliente',
            name='categoria',
            field=models.CharField(choices=[('REG', 'Regular'), ('MAY', 'Mayorista')], default='REG', max_length=3),
        ),
        migrations.CreateModel(
            name='PrecioPorCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('REG', 'Regular'), ('MAY', 'Mayorista')], max_length=3)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='precios_categoria', to='produccion.producto')),
            ],
            options={
                'verbose_name': 'Precio por Categoría',
                'verbose_name_plural': 'Precios por Categoría',
                'unique_together': {('categoria', 'producto')},
            },
        ),
        migrations.DeleteModel(
            name='PrecioCliente',
        ),
    ]
