# Generated by Django 5.2 on 2026-06-06 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distribucion', '0002_correccion_cliente_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planilla',
            options={'ordering': ['-fecha', '-creado_en'], 'verbose_name': 'Planilla', 'verbose_name_plural': 'Planillas'},
        ),
        migrations.AlterUniqueTogether(
            name='planilla',
            unique_together=set(),
        ),
    ]
