# Generated by Django 5.2 on 2026-09-18 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribucion', '0003_quitar_unique_planilla_dia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono'),
        ),
    ]
