# Generated by Django 5.2 on 2026-09-18 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribucion', '0004_alter_cliente_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='averia',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='categoria',
            field=models.CharField(choices=[('REG', 'Regular'), ('MAY', 'Mayorista')], default='REG', max_length=3, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='precioporcategoria',
            name='categoria',
            field=models.CharField(choices=[('REG', 'Regular'), ('MAY', 'Mayorista')], max_length=3, verbose_name='Categoría'),
        ),
    ]
