# Generated by Django 5.2 on 2026-09-18 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribucion', '0005_alter_averia_descripcion_alter_cliente_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='credito',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de pago'),
        ),
    ]
