# Generated by Django 5.2 on 2026-05-30 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Descuadre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('PV', 'Producción vs Ventas'), ('VI', 'Ventas vs Inventario'), ('AC', 'Activos vs Clientes')], max_length=2)),
                ('severidad', models.CharField(choices=[('LEV', 'Leve'), ('MOD', 'Moderado'), ('CRI', 'Crítico')], default='LEV', max_length=3)),
                ('descripcion', models.TextField()),
                ('diferencia', models.DecimalField(decimal_places=2, help_text='Valor numérico de la diferencia detectada', max_digits=12)),
                ('resuelto', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('resuelto_en', models.DateTimeField(blank=True, null=True)),
                ('detectado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='descuadres_detectados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Descuadre',
                'verbose_name_plural': 'Descuadres',
                'ordering': ['resuelto', '-creado_en'],
            },
        ),
    ]
