# Generated by Django 5.2 on 2026-08-30 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='descuadre',
            name='es_automatico',
            field=models.BooleanField(default=False, help_text='True si fue generado por la detección automática (HU-13), no registrado a mano'),
        ),
    ]
