# Generated by Django 5.2 on 2026-09-16 01:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_descuadre_es_automatico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CierreAnual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField(unique=True)),
                ('cerrado', models.BooleanField(default=True)),
                ('fecha_cierre', models.DateTimeField(auto_now_add=True)),
                ('fecha_reapertura', models.DateTimeField(blank=True, null=True)),
                ('cerrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cierres_realizados', to=settings.AUTH_USER_MODEL)),
                ('reabierto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cierres_reabiertos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cierre Anual',
                'verbose_name_plural': 'Cierres Anuales',
                'ordering': ['-anio'],
            },
        ),
    ]
