# Generated by Django 5.2 on 2026-09-17 11:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0003_cierreanual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cierreanual',
            name='fecha_cierre',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
