# Generated by Django 5.2 on 2026-09-18 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0004_alter_cierreanual_fecha_cierre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descuadre',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción'),
        ),
    ]
