# Generated by Django 5.2 on 2026-09-18 03:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0005_alter_descuadre_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cierreanual',
            name='anio',
            field=models.PositiveIntegerField(unique=True, verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='cierreanual',
            name='fecha_cierre',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de cierre'),
        ),
        migrations.AlterField(
            model_name='cierreanual',
            name='fecha_reapertura',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de reapertura'),
        ),
    ]
