# Generated by Django 5.2 on 2026-05-30 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('categoria', models.CharField(choices=[('PST', 'Plástico sin tapa'), ('PCT', 'Plástico con tapa'), ('TAP', 'Tapas'), ('REE', 'Material de reempaque'), ('CIN', 'Cinta'), ('OTR', 'Otro')], max_length=3)),
                ('unidad_medida', models.CharField(max_length=20)),
                ('stock_actual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=0, help_text='Cantidad mínima antes de generar alerta', max_digits=10)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('presentacion', models.CharField(choices=[('PST', 'Paca sin tapa'), ('PCT', 'Paca con tapa'), ('BOT', 'Botellón 20L'), ('B5L', 'Bolsa 5L'), ('B3C', 'Bolsa 300ml'), ('HIE', 'Hielo')], max_length=3, unique=True)),
                ('unidad_medida', models.CharField(default='unidad', max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['presentacion'],
            },
        ),
        migrations.CreateModel(
            name='CompraInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('proveedor', models.CharField(blank=True, max_length=100)),
                ('factura', models.CharField(blank=True, help_text='Número de factura o remisión', max_length=50)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras_registradas', to=settings.AUTH_USER_MODEL)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='produccion.insumo')),
            ],
            options={
                'verbose_name': 'Compra de Insumo',
                'verbose_name_plural': 'Compras de Insumos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('lote', models.CharField(help_text='Código de lote — Res. 2674/2013 BPM', max_length=30, unique=True)),
                ('cantidad_producida', models.PositiveIntegerField()),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producciones_registradas', to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_produccion', to='produccion.producto')),
            ],
            options={
                'verbose_name': 'Registro de Producción',
                'verbose_name_plural': 'Registros de Producción',
                'ordering': ['-fecha', '-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='ConsumoInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumos', to='produccion.insumo')),
                ('produccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='produccion.produccion')),
            ],
            options={
                'verbose_name': 'Consumo de Insumo',
                'verbose_name_plural': 'Consumos de Insumos',
                'unique_together': {('produccion', 'insumo')},
            },
        ),
    ]
