# Generated by Django 5.2 on 2026-06-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='presentacion',
            field=models.CharField(choices=[('PST', 'Paca sin tapa'), ('PCT', 'Paca con tapa'), ('BOT', 'Botellón 20L'), ('B5L', 'Bolsa 5L'), ('B3C', 'Bolsa 300ml'), ('HIE', 'Hielo')], max_length=3),
        ),
    ]
