# Generated by Django 5.2 on 2026-06-10 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0002_quitar_unique_presentacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecetaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_por_unidad', models.DecimalField(decimal_places=4, help_text='Cantidad de este insumo por cada unidad producida', max_digits=10)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recetas', to='produccion.insumo')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receta', to='produccion.producto')),
            ],
            options={
                'verbose_name': 'Receta de Producto',
                'verbose_name_plural': 'Recetas de Productos',
                'ordering': ['producto', 'insumo'],
                'unique_together': {('producto', 'insumo')},
            },
        ),
    ]
