# Generated by Django 5.2 on 2026-08-30 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0003_receta_producto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Regalia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cantidad', models.PositiveIntegerField()),
                ('destinatario', models.CharField(blank=True, help_text='A quién se le entregó (opcional)', max_length=100)),
                ('motivo', models.CharField(choices=[('PRO', 'Promoción'), ('OBS', 'Obsequio a cliente'), ('COR', 'Cortesía institucional'), ('OTR', 'Otro')], default='OTR', max_length=3)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('produccion', models.ForeignKey(blank=True, help_text='Lote de origen, si se conoce (trazabilidad BPM — Res. 2674/2013)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='regalias', to='produccion.produccion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regalias', to='produccion.producto')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regalias_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Regalía',
                'verbose_name_plural': 'Regalías',
                'ordering': ['-fecha', '-creado_en'],
            },
        ),
    ]
