# Generated by Django 5.2 on 2026-09-08 02:15

import django.db.models.deletion
import produccion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0008_finalizar_categoria_unidad_presentacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='unidad_medida',
            field=models.ForeignKey(default=produccion.models._default_unidad_medida_producto, help_text='Unidad en que se cuenta el producto terminado (normalmente "unidad")', on_delete=django.db.models.deletion.PROTECT, related_name='productos_unidad', to='produccion.unidadmedida'),
        ),
    ]
