# Generated by Django 5.2 on 2026-09-18 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0009_alter_producto_unidad_medida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriainsumo',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='categoria',
            field=models.ForeignKey(help_text='Ej: Tapas y sellado — tapas plásticas, anillos de sellado, cinta selladora', on_delete=django.db.models.deletion.PROTECT, related_name='insumos', to='produccion.categoriainsumo', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='presentacion',
            field=models.CharField(choices=[('PAC', 'Paca'), ('BIN', 'Bolsa individual'), ('BOT', 'Botellón'), ('CAJ', 'Caja'), ('BUL', 'Bulto')], help_text='Forma de empaque del producto terminado', max_length=3, verbose_name='Presentación'),
        ),
        migrations.AlterField(
            model_name='unidadmedida',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, verbose_name='Descripción'),
        ),
    ]
