# Generated by Django 5.2 on 2026-09-18 03:40

import django.db.models.deletion
import produccion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0010_alter_categoriainsumo_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='stock_minimo',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cantidad mínima antes de generar alerta. Ej: 3', max_digits=10, verbose_name='Stock mínimo'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='unidad_medida',
            field=models.ForeignKey(help_text='Ej: rollo, kilogramo, millar', on_delete=django.db.models.deletion.PROTECT, related_name='insumos', to='produccion.unidadmedida', verbose_name='Unidad de medida'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='contenido_cantidad',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ej: 300 (junto con la unidad de contenido, ej. ml)', max_digits=8, null=True, verbose_name='Cantidad de contenido'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='contenido_unidad',
            field=models.ForeignKey(blank=True, help_text='Unidad del contenido individual (ej. ml, L, kg)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos_contenido', to='produccion.unidadmedida', verbose_name='Unidad de contenido'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='unidad_medida',
            field=models.ForeignKey(default=produccion.models._default_unidad_medida_producto, help_text='Unidad en que se cuenta el producto terminado (normalmente "unidad")', on_delete=django.db.models.deletion.PROTECT, related_name='productos_unidad', to='produccion.unidadmedida', verbose_name='Unidad de medida'),
        ),
    ]
