# Generated by Django 5.2 on 2026-09-18 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0011_alter_insumo_stock_minimo_alter_insumo_unidad_medida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumoinsumo',
            name='produccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='produccion.produccion', verbose_name='Producción'),
        ),
        migrations.AlterField(
            model_name='regalia',
            name='produccion',
            field=models.ForeignKey(blank=True, help_text='Lote de origen, si se conoce (trazabilidad BPM — Res. 2674/2013)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='regalias', to='produccion.produccion', verbose_name='Producción'),
        ),
    ]
