# Generated by Django 5.2 on 2026-05-30 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivoRetornable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('BOT', 'Botellón 20L'), ('CAN', 'Canastilla')], max_length=3)),
                ('estado', models.CharField(choices=[('PLL', 'En planta — lleno'), ('PVA', 'En planta — vacío'), ('CLI', 'En poder de cliente'), ('BAJ', 'Dado de baja')], default='PVA', max_length=3)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Activo Retornable',
                'verbose_name_plural': 'Activos Retornables',
                'ordering': ['tipo', 'estado'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('momento', models.CharField(choices=[('INI', 'Inicio de jornada'), ('FIN', 'Fin de jornada')], max_length=3)),
                ('tipo_activo', models.CharField(choices=[('BOT', 'Botellón 20L'), ('CAN', 'Canastilla')], max_length=3)),
                ('cantidad_en_planta_lleno', models.PositiveIntegerField(default=0)),
                ('cantidad_en_planta_vacio', models.PositiveIntegerField(default=0)),
                ('cantidad_en_clientes', models.PositiveIntegerField(default=0)),
                ('cantidad_baja', models.PositiveIntegerField(default=0)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_activos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de Activo',
                'verbose_name_plural': 'Movimientos de Activos',
                'ordering': ['-fecha', 'momento'],
                'unique_together': {('fecha', 'momento', 'tipo_activo')},
            },
        ),
    ]
