# Generated by Django 5.2 on 2026-08-30 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BajaActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('motivo', models.CharField(choices=[('ROT', 'Rotura'), ('PER', 'Pérdida'), ('ROB', 'Robo'), ('DET', 'Deterioro'), ('OTR', 'Otro')], default='ROT', max_length=3)),
                ('descripcion', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bajas', to='activos.movimientoactivo')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bajas_activos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Baja de Activo',
                'verbose_name_plural': 'Bajas de Activos',
                'ordering': ['-creado_en'],
            },
        ),
    ]
