# Generated by Django 5.2 on 2026-09-18 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0002_bajaactivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bajaactivo',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
    ]
